server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          # 转发的地址
          uri: http://localhost:8123
          predicates:
            - Path=/api/**

# 开启日志
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: dubbo-springboot-demo-comsumer
  protocaol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848